#!/usr/bin/env bash
# Install the locally built `jean` binary into the user's PATH and application launcher
# on NixOS. Builds a small wrapper that injects LD_LIBRARY_PATH from the flake's dev shell
# so the binary can find webkitgtk / libsoup / etc. at runtime.
#
# Usage: scripts/install-local-nixos.sh
# Prereq: a Tauri release build exists at src-tauri/target/release/jean
#         (run `nix develop -c bun run tauri build` first if not).

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_SRC="$REPO_DIR/src-tauri/target/release/jean"
ICON_SRC="$REPO_DIR/src-tauri/icons/128x128.png"

BIN_DIR="$HOME/.local/bin"
APP_DIR="$HOME/.local/share/applications"
ICON_DIR="$HOME/.local/share/icons/hicolor/128x128/apps"

WRAPPER="$BIN_DIR/jean"
DESKTOP="$APP_DIR/jean.desktop"
ICON_DST="$ICON_DIR/jean.png"

if [[ ! -x "$BIN_SRC" ]]; then
  echo "error: $BIN_SRC not found or not executable." >&2
  echo "build it first:  nix develop -c bun run tauri build" >&2
  exit 1
fi

if [[ ! -f "$ICON_SRC" ]]; then
  echo "error: icon not found at $ICON_SRC" >&2
  exit 1
fi

echo "==> extracting env from nix dev shell (this may take a moment)..."
# Use markers so the shellHook's own stdout (e.g. "dev shell ready") doesn't leak in.
RAW=$(nix develop "$REPO_DIR" --command bash -c \
  'printf "<<<JEAN_LD>>>%s<<<END>>><<<JEAN_GST>>>%s<<<END>>><<<JEAN_GS>>>%s<<<END>>>" "$LD_LIBRARY_PATH" "$GST_PLUGIN_SYSTEM_PATH_1_0" "$GSETTINGS_SCHEMA_DIR"')
LD_PATH=$(printf "%s" "$RAW" | sed -n 's/.*<<<JEAN_LD>>>\(.*\)<<<END>>><<<JEAN_GST>>>.*/\1/p')
GST_PATH=$(printf "%s" "$RAW" | sed -n 's/.*<<<JEAN_GST>>>\(.*\)<<<END>>><<<JEAN_GS>>>.*/\1/p')
GS_PATH=$(printf "%s" "$RAW" | sed -n 's/.*<<<JEAN_GS>>>\(.*\)<<<END>>>.*/\1/p')
if [[ -z "$LD_PATH" ]]; then
  echo "error: failed to extract LD_LIBRARY_PATH from flake dev shell" >&2
  echo "raw output was: $RAW" >&2
  exit 1
fi

mkdir -p "$BIN_DIR" "$APP_DIR" "$ICON_DIR"

echo "==> writing wrapper to $WRAPPER"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Generated by scripts/install-local-nixos.sh — re-run that script to refresh.
export LD_LIBRARY_PATH="$LD_PATH:\${LD_LIBRARY_PATH:-}"
export GST_PLUGIN_SYSTEM_PATH_1_0="$GST_PATH\${GST_PLUGIN_SYSTEM_PATH_1_0:+:\$GST_PLUGIN_SYSTEM_PATH_1_0}"
export GSETTINGS_SCHEMA_DIR="$GS_PATH\${GSETTINGS_SCHEMA_DIR:+:\$GSETTINGS_SCHEMA_DIR}"
export WEBKIT_DISABLE_COMPOSITING_MODE=1
export WEBKIT_DISABLE_DMABUF_RENDERER=1
# Native Wayland is required: the app uses transparent + decorations(false)
# (custom React titlebar). On XWayland that combo produces an empty input
# shape and the window goes dead to clicks. Override with JEAN_GDK_BACKEND=x11 if needed.
export GDK_BACKEND=\${JEAN_GDK_BACKEND:-wayland}
exec "$BIN_SRC" "\$@"
EOF
chmod +x "$WRAPPER"

echo "==> installing icon to $ICON_DST"
install -Dm644 "$ICON_SRC" "$ICON_DST"

echo "==> writing desktop entry to $DESKTOP"
cat > "$DESKTOP" <<EOF
[Desktop Entry]
Type=Application
Name=Jean
Comment=Jean desktop app
Exec=$WRAPPER %U
Icon=jean
Terminal=false
Categories=Development;
StartupWMClass=Jean
EOF

if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$APP_DIR" >/dev/null 2>&1 || true
fi
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -t "$HOME/.local/share/icons/hicolor" >/dev/null 2>&1 || true
fi

echo
echo "done."
echo "  binary wrapper: $WRAPPER"
echo "  desktop entry:  $DESKTOP"
echo "  icon:           $ICON_DST"
echo
case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "note: $BIN_DIR is not on your PATH — add it to your shell rc to launch via 'jean'." ;;
esac
